name = "icp-pulse-ai-gateway"
main = "src/worker.ts"
compatibility_date = "2024-10-01"

# Durable Objects configuration (using SQLite for free plan compatibility)
[durable_objects]
bindings = [
  { name = "AI_CACHE", class_name = "AICacheDurableObject" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["AICacheDurableObject"]

# Environment variables (non-sensitive)
[vars]
CACHE_RETENTION_DAYS = "90"

# Secrets (set with: wrangler secret put <NAME>)
# OPENAI_API_KEY - OpenAI API key
# SIGNING_SECRET - HMAC signing secret for ICP verification

# Optional: Scheduled cleanup (runs weekly on Sundays at midnight UTC)
# [triggers]
# crons = ["0 0 * * 0"]
